version: 2

project: "pfee-zama"

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  version: 3.10
  install:
    - requirements: requirements.txt

sphinx:
  configuration: docsource/conf.py
